[programs.localnet]
spin_win = "6LyE69h6v9ZBfmXNcD5QX9qhxTB2JWwzCgQpzooYML6D"

[programs.devnet]
spin_win = "6LyE69h6v9ZBfmXNcD5QX9qhxTB2JWwzCgQpzooYML6D"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
